name:                CategoriesWorkingHacker
version:             0.1.0.0
github:              "jmgimeno/categories-working-hacker"
license:             MIT
author:              "Juan Manuel Gimeno Illa"
maintainer:          "jmgimeno@gmail.com"
copyright:           "2018 Juan Manuel Gimeno Illa"

extra-source-files:
- README.md
- ChangeLog.md
- LICENSE

ghc-options: -Wall -Werror

description: Please see the README on Github at <https://github.com/jmgimeno/categories-working-hacker#readme>

dependencies:
- base >= 4.10 && < 4.11

library:
  source-dirs: src

tests:
  exercise-test-suite:
    source-dirs: tests/tasty
    main: Main.hs
    dependencies:
    - base        >= 4.10 && < 4.11
    - tasty       >= 1.0 && < 1.1
    - tasty-hunit >= 0.10 && < 0.11
    - CategoriesWorkingHacker
  hlint-code:
    source-dirs: tests/hlint
    main: Main.hs
    dependencies:
    - base        >= 4.10 && < 4.11
    - hlint       >= 2.1  && < 2.2